{
	"name": "CVE-2023-39661",
	"seq": "2023-39661",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20230807"
	},
	"desc": "An issue in pandas-ai v.0.9.1 and before allows a remote attacker to execute arbitrary code via the _is_jailbreak function.",
	"refs": [
		{
			"text": "https://github.com/gventuri/pandas-ai/issues/410",
			"source": "MISC",
			"url": "https://github.com/gventuri/pandas-ai/issues/410"
		}
	],
	"votes": {}
}
