{
	"name": "CVE-2024-27351",
	"seq": "2024-27351",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20240225"
	},
	"desc": "In Django 3.2 before 3.2.25, 4.2 before 4.2.11, and 5.0 before 5.0.3, the django.utils.text.Truncator.words() method (with html=True) and the truncatewords_html template filter are subject to a potential regular expression denial-of-service attack via a crafted string. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232 and CVE-2023-43665.",
	"refs": [
		{
			"text": "https://www.djangoproject.com/weblog/2024/mar/04/security-releases/",
			"source": "CONFIRM",
			"url": "https://www.djangoproject.com/weblog/2024/mar/04/security-releases/"
		},
		{
			"text": "FEDORA-2024-2ec03ca8cb",
			"source": "FEDORA",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SN2PLJGYSAAG5KUVIUFJYKD3BLQ4OSN6/"
		},
		{
			"text": "FEDORA-2024-5c7fb64c74",
			"source": "FEDORA",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/D2JIRXEDP4ZET5KFMAPPYSK663Q52NEX/"
		},
		{
			"text": "FEDORA-2024-84fbbbb914",
			"source": "FEDORA",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZQJOMNRMVPCN5WMIZ7YSX5LQ7IR2NY4D/"
		},
		{
			"text": "https://docs.djangoproject.com/en/5.0/releases/security/",
			"source": "MISC",
			"url": "https://docs.djangoproject.com/en/5.0/releases/security/"
		},
		{
			"text": "https://groups.google.com/forum/#!forum/django-announce",
			"source": "MISC",
			"url": "https://groups.google.com/forum/#%21forum/django-announce"
		},
		{
			"text": "[oss-security] 20240304 Django: CVE-2024-27351: Potential regular expression denial-of-service in django.utils.text.Truncator.words()",
			"source": "MLIST",
			"url": "http://www.openwall.com/lists/oss-security/2024/03/04/1"
		}
	],
	"votes": {}
}
