{
	"name": "CVE-2017-14503",
	"seq": "2017-14503",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20170917"
	},
	"desc": "libarchive 3.3.2 suffers from an out-of-bounds read within lha_read_data_none() in archive_read_support_format_lha.c when extracting a specially crafted lha archive, related to lha_crc16.",
	"refs": [
		{
			"text": "DSA-4360",
			"source": "DEBIAN",
			"url": "https://www.debian.org/security/2018/dsa-4360"
		},
		{
			"text": "GLSA-201908-11",
			"source": "GENTOO",
			"url": "https://security.gentoo.org/glsa/201908-11"
		},
		{
			"text": "https://bugs.debian.org/875960",
			"source": "MISC",
			"url": "https://bugs.debian.org/875960"
		},
		{
			"text": "https://github.com/libarchive/libarchive/issues/948",
			"source": "MISC",
			"url": "https://github.com/libarchive/libarchive/issues/948"
		},
		{
			"text": "[debian-lts-announce] 20181129 [SECURITY] [DLA 1600-1] libarchive security update",
			"source": "MLIST",
			"url": "https://lists.debian.org/debian-lts-announce/2018/11/msg00037.html"
		},
		{
			"text": "RHSA-2019:2298",
			"source": "REDHAT",
			"url": "https://access.redhat.com/errata/RHSA-2019:2298"
		},
		{
			"text": "RHSA-2019:3698",
			"source": "REDHAT",
			"url": "https://access.redhat.com/errata/RHSA-2019:3698"
		},
		{
			"text": "USN-3736-1",
			"source": "UBUNTU",
			"url": "https://usn.ubuntu.com/3736-1/"
		}
	],
	"votes": {}
}
