{
	"name": "CVE-2019-10904",
	"seq": "2019-10904",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20190406"
	},
	"desc": "Roundup 1.6 allows XSS via the URI because frontends/roundup.cgi and roundup/cgi/wsgi_handler.py mishandle 404 errors.",
	"refs": [
		{
			"text": "https://bugs.python.org/issue36391",
			"source": "MISC",
			"url": "https://bugs.python.org/issue36391"
		},
		{
			"text": "https://github.com/python/bugs.python.org/issues/34",
			"source": "MISC",
			"url": "https://github.com/python/bugs.python.org/issues/34"
		},
		{
			"text": "https://www.openwall.com/lists/oss-security/2019/04/05/1",
			"source": "MISC",
			"url": "https://www.openwall.com/lists/oss-security/2019/04/05/1"
		},
		{
			"text": "[debian-lts-announce] 20190407 [SECURITY] [DLA 1750-1] roundup security update",
			"source": "MLIST",
			"url": "https://lists.debian.org/debian-lts-announce/2019/04/msg00009.html"
		},
		{
			"text": "[oss-security] 20190407 Re: XSS in roundup bug tracker 404 page",
			"source": "MLIST",
			"url": "http://www.openwall.com/lists/oss-security/2019/04/07/1"
		}
	],
	"votes": {}
}
