{
  "name": "CVE-2015-5145",
  "seq": "2015-5145",
  "type": "CAN",
  "status": "Candidate",
  "phase": {
    "text": "Assigned",
    "date": "20150629"
  },
  "desc": "validators.URLValidator in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors.",
  "refs": [
    {
      "text": "75691",
      "source": "BID",
      "url": "http://www.securityfocus.com/bid/75691"
    },
    {
      "text": "https://www.djangoproject.com/weblog/2015/jul/08/security-releases/",
      "source": "CONFIRM",
      "url": "https://www.djangoproject.com/weblog/2015/jul/08/security-releases/"
    },
    {
      "text": "GLSA-201510-06",
      "source": "GENTOO",
      "url": "https://security.gentoo.org/glsa/201510-06"
    },
    {
      "text": "1032820",
      "source": "SECTRACK",
      "url": "http://www.securitytracker.com/id/1032820"
    }
  ],
  "votes": {}
}
