{
	"name": "CVE-2016-10127",
	"seq": "2016-10127",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20170110"
	},
	"desc": "PySAML2 allows remote attackers to conduct XML external entity (XXE) attacks via a crafted SAML XML request or response.",
	"refs": [
		{
			"text": "95376",
			"source": "BID",
			"url": "http://www.securityfocus.com/bid/95376"
		},
		{
			"text": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716",
			"source": "MISC",
			"url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716"
		},
		{
			"text": "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b",
			"source": "MISC",
			"url": "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b"
		},
		{
			"text": "https://github.com/rohe/pysaml2/issues/366",
			"source": "MISC",
			"url": "https://github.com/rohe/pysaml2/issues/366"
		},
		{
			"text": "https://github.com/rohe/pysaml2/pull/379",
			"source": "MISC",
			"url": "https://github.com/rohe/pysaml2/pull/379"
		},
		{
			"text": "[oss-security] 20170119 Re: CVE request: python-pysaml2 XML external entity attack",
			"source": "MLIST",
			"url": "http://www.openwall.com/lists/oss-security/2017/01/19/5"
		}
	],
	"votes": {}
}
