{
  "name": "CVE-2020-13596",
  "seq": "2020-13596",
  "type": "CAN",
  "status": "Candidate",
  "phase": {
    "text": "Assigned",
    "date": "20200526"
  },
  "desc": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. Query parameters generated by the Django admin ForeignKeyRawIdWidget were not properly URL encoded, leading to a possibility of an XSS attack.",
  "refs": [
    {
      "text": "https://security.netapp.com/advisory/ntap-20200611-0002/",
      "source": "CONFIRM",
      "url": "https://security.netapp.com/advisory/ntap-20200611-0002/"
    },
    {
      "text": "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/",
      "source": "CONFIRM",
      "url": "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/"
    },
    {
      "text": "DSA-4705",
      "source": "DEBIAN",
      "url": "https://www.debian.org/security/2020/dsa-4705"
    },
    {
      "text": "FEDORA-2020-c2639662af",
      "source": "FEDORA",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/"
    },
    {
      "text": "https://docs.djangoproject.com/en/3.0/releases/security/",
      "source": "MISC",
      "url": "https://docs.djangoproject.com/en/3.0/releases/security/"
    },
    {
      "text": "https://groups.google.com/forum/#!msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ",
      "source": "MISC",
      "url": "https://groups.google.com/forum/#%21msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ"
    },
    {
      "text": "https://www.oracle.com/security-alerts/cpujan2021.html",
      "source": "MISC",
      "url": "https://www.oracle.com/security-alerts/cpujan2021.html"
    },
    {
      "text": "USN-4381-1",
      "source": "UBUNTU",
      "url": "https://usn.ubuntu.com/4381-1/"
    },
    {
      "text": "USN-4381-2",
      "source": "UBUNTU",
      "url": "https://usn.ubuntu.com/4381-2/"
    }
  ],
  "votes": {}
}
