{
	"name": "CVE-2021-32285",
	"seq": "2021-32285",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20210507"
	},
	"desc": "An issue was discovered in gravity through 0.8.1. A NULL pointer dereference exists in the function list_iterator_next() located in gravity_core.c. It allows an attacker to cause Denial of Service.",
	"refs": [
		{
			"text": "https://github.com/marcobambini/gravity/issues/319",
			"source": "MISC",
			"url": "https://github.com/marcobambini/gravity/issues/319"
		}
	],
	"votes": {}
}
